name: Recent Blog

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-readme-feed
    steps:
      - uses: actions/checkout@v4
      - uses: sarisia/actions-readme-feed@v1
        with:
          url: "https://guoqi.dev/rss.xml"
          file: "README.md"
      - uses: sarisia/actions-commit@master
